[functions]
  external_node_modules = ["express", "serverless-http", "@google/generative-ai"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
